#!/usr/bin/with-contenv sh

cat << EOF > /etc/fluentd/fluent.conf
<source>
  @type  forward
  @id   input
  port  24224
</source>

<match **>
  @type aws-elasticsearch-service
  logstash_format true
  logstash_dateformat %Y-%m
  logstash_prefix \${tag}
  include_tag_key true
  tag_key tag
  <buffer>
    @type file
    path /tmp
    flush_interval 60s
    overflow_action drop_oldest_chunk
    retry_timeout 1h
    retry_max_times 3
  </buffer>

  <endpoint>
    url ${ELASTIC_HOST:=elasticsearch}
    region ${ELASTIC_REGION:=ap-northeast-1}
  </endpoint>

</match>

EOF
